### ISSUE TITLE
Limn(of:) an URL causes an EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by julasamer** [diogopribeiro/Limn#12]
In Limn+Objc.swift line 10.

Test:

    Limn(of: URL(string: "http://foo.com")).dump()

Not sure what's so evil about reading the `_urlString` ivar, but it doesn't work.

**Comment by diogopribeiro** [comment]
Thanks for the report, I've included the line above on a test case.

I'm still working on the support for Objective-C, a new update should come out in a couple of days with improved support for decoding of `NSObject`s. The crash above should be resolved as well.

**Comment by julasamer** [comment]
Nice, thank you!

**Comment by diogopribeiro** [comment]
Should be fixed as of v0.9.3.
